// <auto-generated />
using MCV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MCV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221128131818_Seeded database")]
    partial class Seededdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MCV.Models.PersonData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PeopleData");

                    b.HasData(
                        new
                        {
                            Id = "2b38f403-a45c-42f1-bf84-0abc30e56844",
                            City = "Göteborg",
                            Name = "Andreas Lyckholm",
                            PhoneNumber = "0768382888"
                        },
                        new
                        {
                            Id = "2c0cf7ed-0b66-47e2-b76e-f831d56d6e0b",
                            City = "Göteborg",
                            Name = "Christoffer Lyckholm",
                            PhoneNumber = "0761717777"
                        },
                        new
                        {
                            Id = "cea6c7ba-15c3-419e-b6ac-e0d3a3a29c77",
                            City = "Stockholm",
                            Name = "Sten Sture",
                            PhoneNumber = "0808807652"
                        },
                        new
                        {
                            Id = "8b179a3e-b5ca-4dfb-9f82-68da84839f10",
                            City = "Stockholm",
                            Name = "Sven Svensson",
                            PhoneNumber = "085676832"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
